### ISSUE TITLE
Doesn't go well with vim-visual-multi

### ISSUE THREAD

**Issue by eyalk11** [vds2212/vim-remotions#13]
See https://github.com/mg979/vim-visual-multi/issues/280

**Comment by vds2212** [comment]
Thanks for reporting this problem. I'll try to reproduce it on my end.

**Comment by vds2212** [comment]
Here is the problem I have reproduced:

If you register the h and l motions with vim-remotions:

```
let g:remotions_motions = {
      \ 'TtFf' : {},
      \ 'char' : {
      \    'backward' : 'h',
      \    'forward' : 'l',
      \    'repeat_if_count' : 1,
      \ },
```

When you are using [vim-visual-multi](https://github.com/mg979/vim-visual-multi) when you are using these motion in multi cursor mode:
- the cursor only move for the current word/cursor and not for all the cursors
- when inserting text after the user (e.g. using the a operator) the text is insert like if the cursor has not been moved.

I believe the reason is that [vim-visual-multi] hijack the motions (i.e. introduces their own mapping for h and l) and these mapping get confused with the mapping for h and l that vim-remotions introduced.

I there is a solution I supposed it is in vim-visual-multi.

I had a look at the code but it seems rather complex.

Remark: If you don't have vim-remotions remapping h and l it seems to work fine with vim-visual-multi.

**Comment by vds2212** [comment]
I there is a solution I supposed it is in vim-visual-multi.
