### ISSUE TITLE
Examples of calling fuctions (eg Leap motions)

### ISSUE THREAD

**Issue by HaleTom** [vds2212/vim-remotions#2]
I am a long-time user of repmo, but I'm trying to find a way of getting it to work with the excellent and commonly used https://github.com/ggandor/leap.nvim.

Would you provide an example on how to repeat leap's `s` (forward) and `S` (backwards) searches?

**Comment by vds2212** [comment]
I'll install leap and make it work ;-)

**Comment by HaleTom** [comment]
That's absolutely epic!!!  Thanks a bunch!

**Comment by vds2212** [comment]
I have installed leap and after some test I reformulate your demand to make sure I have the correct understanding.

The leap repeat operation is tricky and leap has provided a special API to allow the repetition but it enter in conflict with remotion such that it is not usable.

The question: Is how to use both the leap API to get the repetition of leap and the repetition of remotion?

Do I have the correct understanding?

**Comment by vds2212** [comment]
I have tried but at first glance it looks quite difficult in particular to make a code that is working for both Vim and Neovim. Leap is developed in Lua and the mapping for ',' and ';' need to be hijacked such that they do not conflict with remotions mapping but since they are defined as local Lua leap methods I suppose it is difficult to highjack them.

I don't give up but it is a difficult one :-|

**Comment by vds2212** [comment]
I have made a new version that supports [leap](https://github.com/ggandor/leap.nvim) and I have documented the way to configured it. Let me know if it works for you.

**Comment by vds2212** [comment]
I have made a new version that supports leap and described in the Readme.md how to configure for leap.
